# -*- coding: utf-8 -*-
"""CONVERTIRTEMPERATURA.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qqT6zOStWWk9cM7cSewWMUa-ZFc5WwZJ
"""



def convertir_a_fahrenheit(celsius):
  return (celsius * 9 / 5) + 32

c = float(input("Ingrese la temperatura en grados Celsius: "))
fahrenheit = convertir_a_fahrenheit(c)

print(f"{c}°C equivale a {fahrenheit}°F")