# -*- coding: utf-8 -*-
"""MAYOROMENORDEEDAD.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WrsEXgQ4fKvTFAcIpWLBcAk65dkfoYR3
"""

def verificar_mayoria_edad(edad):
  if edad >= 18:
    return "Mayor de edad"
  else:
    return "Menor de edad"

edad = int(input("Ingrese su edad: "))
resultado = verificar_mayoria_edad(edad)

print(f"La persona es: {resultado}")