# -*- coding: utf-8 -*-
"""SALUDO PERSONALIZADO.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_FkMG_7yf7PtIeN9sIiaNSUtlDEgzyW
"""

# Esta función no usa 'return', solo imprime.
def saludar(nombre, edad):
  print(f"¡Hola, {nombre}! Veo que tienes {edad} años.")

nombre_usuario = input("Ingrese su nombre: ")
edad_usuario = int(input("Ingrese su edad: "))

# Se llama a la función para que realice la acción
saludar(nombre_usuario, edad_usuario)